site_name: ArrayFire.js Documentation
pages:
- Home: index.md
- Statics: statics.md
- Classes:
  - AFArray: AFArray.md
  - Dim4: Dim4.md
  - Seq: Seq.md
  - Complex: Complex.md
- Functions:
  - Platform and Device managing: devices.md
  - Functions to create arrays: create.md
  - Helper function for arrays: helpers.md
theme: united
repo_url: https://github.com/arrayfire/arrayfire_js