site_name: Fire.js Documentation
pages:
- Home: index.md
- Statics:
  - dtype: dtype.md
  - source: source.md
- Classes:
  - AFArray: AFArray.md
- Functions:
  - Managing Devices: devices.md
theme: united
repo_url: https://github.com/unbornchikken/fire-js